### ISSUE TITLE
Diagram

### ISSUE THREAD

**Issue by aigyz** [aliskhakov/doublefinder#1]
Hi! Maybe this diagram would make easy to understand your project.
![diagram](https://cloud.githubusercontent.com/assets/15369986/12699407/f163437a-c7ca-11e5-9dc7-1c6f069cfcb9.png)
Astah source:
[DFDiagram.asta.zip](https://github.com/aliskhakov/doublefinder/files/111063/DFDiagram.asta.zip)

**Comment by aliskhakov** [comment]
Thanks! Added to readme. https://github.com/aliskhakov/doublefinder/commit/97229da0222503e918786897e00ebd7c160f15ad
